services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://luma:luma@postgres:5432/luma
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - luma-backend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        API_URL: /api
    depends_on:
      - backend
    ports:
      - "8080:80"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: luma
      POSTGRES_USER: luma
      POSTGRES_PASSWORD: luma
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luma"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
volumes:
  postgres_data:
