version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://luma:luma@postgres:5432/luma
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: luma
      POSTGRES_USER: luma
      POSTGRES_PASSWORD: luma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  postgres_data:
