apiVersion: apps/v1
kind: Deployment
metadata:
  name: luma-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luma-backend
  template:
    metadata:
      labels:
        app: luma-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image }}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://luma:luma@postgres:5432/luma
        - name: REDIS_URL
          value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: luma-backend
spec:
  selector:
    app: luma-backend
  ports:
  - port: 80
    targetPort: 8000
