apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luma-ingress
spec:
  rules:
  - host: luma.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: luma-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: luma-backend
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: luma-backend
            port:
              number: 80
